version: '3'
services:
  cassandra:
    hostname: cassandra
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - '9042:9042'
    volumes:
      - './database/:/migrations'
      - '/data/db/:/var/lib/cassandra'

  processor:
    build: data-processing/
    volumes:
      - '/data/datasets/:/home/user/Documents/dataSets/'

  api:
    hostname: apiserver
    build: data-retrieval/
    ports:
      - '3000:3000'
    environment:
      - PYTHONUNBUFFERED=0

  web:
    build: frontend/
    network_mode: "host"
    ports:
      - '0.0.0.0:80:80'
